"""empty message

Revision ID: e2e2930aae64
Revises: 7422b277b439
Create Date: 2022-01-01 16:16:02.392677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2e2930aae64'
down_revision = '7422b277b439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cc_code', sa.String(length=3), nullable=True))
    op.alter_column('orders', 'items',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('orders', 'city',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)
    op.alter_column('orders', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('orders', 'zipCode',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('orders', 'credit_card',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('orders', 'expiration_date',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.alter_column('orders', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('orders', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('reviews', sa.Column('reviewImg', sa.String(length=255), nullable=True))
    op.drop_column('reviews', 'ratingImg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('ratingImg', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'reviewImg')
    op.alter_column('orders', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('orders', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('orders', 'expiration_date',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.alter_column('orders', 'credit_card',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('orders', 'zipCode',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('orders', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('orders', 'city',
               existing_type=sa.VARCHAR(length=75),
               nullable=True)
    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('orders', 'items',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('orders', 'cc_code')
    # ### end Alembic commands ###
