"""empty message

Revision ID: 7422b277b439
Revises: fd5990045fe5
Create Date: 2022-01-01 15:45:39.483611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7422b277b439'
down_revision = 'fd5990045fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('city', sa.String(length=75), nullable=True))
    op.add_column('orders', sa.Column('state', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('zipCode', sa.String(length=5), nullable=True))
    op.alter_column('orders', 'items',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('orders', 'credit_card',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('orders', 'expiration_date',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.alter_column('orders', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('orders', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('reviews', sa.Column('ratingImg', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'ratingImg')
    op.alter_column('orders', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('orders', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('orders', 'expiration_date',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.alter_column('orders', 'credit_card',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('orders', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('orders', 'items',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('orders', 'zipCode')
    op.drop_column('orders', 'state')
    op.drop_column('orders', 'city')
    # ### end Alembic commands ###
